version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
        - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  site:
    depends_on:
      - apollo
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./fl-site
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./fl-site:/app

  apollo:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./fl-apollo
    volumes:
      - /app/node_modules
    ports:
      - '4000:4000'
    depends_on:
      - mongo
