version: '3'
services:
  mongo:
    image: 'mongo:latest'
  site:
    depends_on:
      - mongo
      - apollo
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./fl-site
    # ports:
    #   - '3050:80'
    volumes:
      - /app/node_modules
      - ./server:/app
  apollo:
    build:
      dockerfile: Dockerfile.dev
      context: ./fl-apollo
    volumes:
      - /app/node_modules
