version: '3'
services:
  mongo:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  site:
    depends_on:
      - mongo
      - apollo
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./fl-site
    ports:
      - '3000:80'
    volumes:
      - /app/node_modules
      - ./server:/app
  apollo:
    build:
      dockerfile: Dockerfile.dev
      context: ./fl-apollo
    volumes:
      - /app/node_modules
